services: 
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db



  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on: 
    - mongodb  

  redis:
    image: redis:7
    container_name: redis
    volumes:
    - redis: /data   



  mysql:
    image: mysql:v1
    container_name: mysql
    volumes:
    - mysql: /var/lib/mysql


  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
    - rabbitmq: /var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    

  user:
    image: user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb

  cart:
    image: cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue

  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
    - cart
    - mysql

  payment:
    image: payment:v1
    container_name: payment
    depends_on:
    - cart
    - user
    - rabbitmq


  frontend:
    image: frontend:v1
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment    


networks:
  default:
    driver: bridge
    name: roboshop
    external: false

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:    

















# services:
#   catalogue:
#     build:
#       context: ./catalogue
#       dockerfile: Dockerfile
#     image: catalogue:v1
#     container_name: catalogue
#     depends_on:
#     - mongodb
#   mongodb:
#     build:
#       context: ./mongodb
#       dockerfile: Dockerfile
#     image: mongodb:v1
#     container_name: mongodb
#     volumes:
#     - mongodb:/data/db
#   redis:
#     build:
#       context: ./mongodb
#       dockerfile: Dockerfile
#     image: redis:7.0
#     container_name: redis
#     volumes:
#     - redis:/data
#   mysql:
#     build:
#       context: ./mysql
#       dockerfile: Dockerfile
#     image: mysql:v1
#     container_name: mysql
#     volumes:
#     - mysql:/var/lib/mysql
#   rabbitmq:
#     build:
#       context: ./rabbitmq
#       dockerfile: Dockerfile
#     image: rabbitmq:3
#     container_name: rabbitmq
#     volumes: # -v rabbitmq:/var/lib/rabbitmq
#     - rabbitmq:/var/lib/rabbitmq
#     environment:
#       RABBITMQ_DEFAULT_USER: roboshop
#       RABBITMQ_DEFAULT_PASS: roboshop123
#   user:
#     build:
#       context: ./user
#       dockerfile: Dockerfile
#     image: user:v1
#     container_name: user
#     depends_on:
#     - mongodb
#     - redis
#   cart:
#     build:
#       context: ./cart
#       dockerfile: Dockerfile
#     image: cart:v1
#     container_name: cart
#     depends_on:
#     - redis
#     - catalogue
#   shipping:
#     build:
#       context: ./shipping
#       dockerfile: Dockerfile
#     image: shipping:v1
#     container_name: shipping
#     depends_on:
#     - mysql
#     - cart
#   payment:
#     build:
#       context: ./payment
#       dockerfile: Dockerfile
#     image: payment:v1
#     container_name: payment
#     depends_on:
#     - rabbitmq
#     - cart
#     - user
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     image: frontend:v1
#     container_name: frontend
#     ports:
#     - "80:80"
#     depends_on:
#     - catalogue
#     - user
#     - cart
#     - shipping
#     - payment
# networks:
#   default:
#     driver: bridge
#     name: roboshop
#     external: false # true if you have created network manually using docker network command
# volumes:
#   mongodb: # docker volume create mongodb. /var/lib/docker/volumes
#   redis:
#   mysql:
#   rabbitmq: